// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	CreatedAt string    `json:"created_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedAt *string   `json:"updated_at,omitempty"`
	Vid       int       `json:"vid"`
	ID        string    `json:"id"`
	Number    string    `json:"number"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	UpdatedBy *string   `json:"updated_by,omitempty"`
	Config    []*Config `json:"config,omitempty"`
}

type Config struct {
	ID        int     `json:"id"`
	CompanyID *string `json:"company_id,omitempty"`
	Key       *string `json:"key,omitempty"`
	Value     *string `json:"value,omitempty"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
